# -*- coding: utf-8 -*-
"""Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m7jLqNlCNBesG5700k9KPqIIk91CZrH4
"""

s = input('Enter the lottery word : ')
all_freq = {}
for i in s:
    if i in all_freq:
        all_freq[i] += 1
    else:
        all_freq[i] = 1
res = max(all_freq, key = all_freq.get) 
print ("The maximum of all characters in s is : " + str(res))

